добавляет параметры запроса на страницу лота
htmlacademy-php/225742-yeticave-12 pull request #10
Opened 2021-08-06 13:12 UTC by summertime-fms

2021-08-06 19:05 UTC, freedayko requested changes

2021-08-06 19:05 UTC, alexpalyan commented on functions.php
>      $con = set_connection();
Не нужно каждый раз при запросе создавать новое соединение, у тебя было записано передача соединения через параметр, зачем это убирал?...

2021-08-06 19:05 UTC, alexpalyan commented on functions.php
> +    } else if ($is_one) {
сделай лучше отдельную функцию для такого... Очень похвально что ты пытаешься сделать меньше дублирования кода. к сожалению, для данного случая не лучший вариант... много не сэкономишь, зато гибче будет код и проще поддерживать если отдльно есть функция на получения массива строк и отдельно функция на получение строки.

2021-08-06 19:05 UTC, freedayko commented on lot.php
> +    $lot = get_lot($_GET['id']);
Необходима проверка входящего параметра, например, через filter_input

2021-08-06 19:05 UTC, freedayko commented on functions.php
> +    $lot_query = 'SELECT name, description, start_cost, img_link, termination_date, category, step FROM lots l JOIN categories ON category_id = categories.id WHERE l.id = ' . $id ;
любые входящие данные перед вставкой в запрос обязательно нужно обработать

2021-08-06 20:16 UTC, summertime-fms commented on functions.php
> +    $lot_query = 'SELECT name, description, start_cost, img_link, termination_date, category, step FROM lots l JOIN categories ON category_id = categories.id WHERE l.id = ' . $id ;
добавил intval в lot.php при передаче аргумента id

2021-08-09 11:37 UTC, freedayko commented on functions.php
>      } else {
в данном случае else можно опустить, просто return

2021-08-09 11:37 UTC, freedayko commented on lot.php
> +}
Подумай как можно сделать без вложенности и повторения

2021-08-09 11:38 UTC, merged