Module4 task1
htmlacademy-php/225742-yeticave-12 pull request #7
Opened 2021-07-19 06:20 UTC by summertime-fms

2021-07-21 11:32 UTC, ademaro commented on functions.php
>      if ($number > 1000) {
если не будет этого условия — что-то поменяется в форматировании вывода?)

2021-07-21 11:32 UTC, ademaro commented on helpers.php
> +        return $result = '';
`return '';` тогда уж)

2021-07-21 11:33 UTC, ademaro commented on schema.sql
> +	category VARCHAR(25) UNIQUE,
не слишком ли мало 25 символов на название категории?

2021-07-21 11:33 UTC, ademaro commented on schema.sql
> +  lot_description VARCHAR(250),
имя может быть больше теоретически, описание — вообще TEXT предлагаю сделать

2021-07-21 12:23 UTC, ademaro requested changes
Давай немного подправим. Кроме основных правок — пересмотри ограничения на длину текстовых полей, очень много у тебя очень коротких...

2021-07-21 12:23 UTC, ademaro commented on schema.sql
> +  category VARCHAR(25)
почему VARCHAR? Мы же тут будем хранить id категории

2021-07-21 12:23 UTC, ademaro commented on schema.sql
> +	creation_date TIMESTAMP,
можно автоматически писать текущую дату при создании записи, посмотри как делается

2021-07-21 12:23 UTC, ademaro commented on schema.sql
> +  lot_id INT UNIQUE,
почему uniq?

2021-07-21 12:23 UTC, ademaro commented on schema.sql
> +  bets INT
в пользователях не надо хранить ставки и лоты) это в лотах и ставках будем хранить пользователей))

2021-07-21 12:23 UTC, ademaro commented on schema.sql
> +CREATE INDEX bets_index ON bets(creation_date, amount, lot_id, author_id);
создавать индексы можем сразу при описании поля (как ты делал с unique)

2021-07-23 16:10 UTC, ademaro commented on functions.php
> +        return ceil($number);
подожди, мы не в ту сторону свернули)) Зачем else вообще?))
Почитай критерий [Д7](https://up.htmlacademy.ru/php/12/criteries#d7), мы тут его нарушили

2021-07-23 16:11 UTC, ademaro commented on functions.php
> +    function get_time_in_hours($date) {
а чего с отступами?

2021-07-23 16:14 UTC, ademaro commented on schema.sql
> +	creation_date           TIMESTAMP,
`creation_date           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,` — по-умолчанию, вроде, обсуждали это, не?

2021-07-23 16:14 UTC, ademaro commented on schema.sql
> +	creation_date           TIMESTAMP,
кстати, скажи чем отличается TIMESTAMP от DATETIME?)

2021-07-23 16:15 UTC, ademaro commented on schema.sql
> +  category                INT
category_id что бы не путаться

2021-07-23 16:15 UTC, ademaro commented on schema.sql
> +  creation_date           DATETIME,
давай определимся или DATETIME или TIMESTAMP во всех таблицах

2021-07-23 16:16 UTC, ademaro commented on schema.sql
> +  INDEX(amount)
зачем индексируешь поле?

2021-07-23 16:17 UTC, ademaro commented on schema.sql
> +  user_password           VARCHAR(75),
почему именно 75?

2021-07-23 16:17 UTC, ademaro requested changes
ещё поработать надо)

2021-07-24 07:03 UTC, summertime-fms commented on functions.php
>      if ($number > 1000) {
https://skr.sh/s9CqnX2L32Z

2021-07-24 07:03 UTC, summertime-fms commented on functions.php
>      if ($number > 1000) {
Я не понимаю на что ты намекаешь

2021-07-27 00:19 UTC, merged